### ISSUE TITLE
No push notification received with new training schedule

### ISSUE THREAD

**Issue by dougwurtele** [dougwurtele/IFTTT-Augmentor#3]
A push notification wasn't send when a new training schedule was received.

**Comment by dougwurtele** [comment]
Exception from log:

Failed to process training schedule file: /Users/dougwurtele/Dropbox/IFTTT/Gmail/michaelsmitchell34mil@mailmil/TS_3-4_Dec.docm: java.lang.ClassCastException: Could not truncate org.wurtele.ifttt.model.TrainingScheduleEntry@73510b0b
        at org.apache.commons.lang3.time.DateUtils.truncate(DateUtils.java:872)
        at org.wurtele.ifttt.watchers.TrainingScheduleWatcher.processWordFile(TrainingScheduleWatcher.java:185)
        at org.wurtele.ifttt.watchers.TrainingScheduleWatcher.handleCreate(TrainingScheduleWatcher.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.wurtele.ifttt.watchers.base.DirectoryWatcher.watch(DirectoryWatcher.java:122)
        at org.wurtele.ifttt.watchers.base.WatchRunner.run(WatchRunner.java:17)
        at java.lang.Thread.run(Thread.java:745)

**Comment by dougwurtele** [comment]
Attempted to truncate a training schedule entry instead of the end date for that entry.
